### ISSUE TITLE
Missing page should show a 404, not a blank page with an Edit icon?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [ignitionrobotics/docs#29]
Update: From @chapulina 

> I think that the page you're trying to edit should show a 404 instead of a title and pencil:

---

As I was investigating #28, I tried clicking on the Edit Icon (<img src="https://user-images.githubusercontent.com/26719449/83339185-46d0b380-a299-11ea-82a5-f0e797b96c15.png" height="20px"/>), and it took me to the following link which is broken:
<https://github.com/ignitionrobotics/docs/blob/master/>

I think the correct link should have been either:
<https://github.com/ignitionrobotics/docs/blob/master/releases.md>
or
<https://github.com/ignitionrobotics/docs/tree/master/> ?

Current commit: 198e1f9

**Comment by chapulina** [comment]
I think that the page you're trying to edit should show a 404 instead of a title and pencil:

https://ignitionrobotics.org/docs/releases

This is the correct page and its edit button redirects to the correct GitHub file for me:

https://ignitionrobotics.org/docs/all/releases

:arrow_down: 

https://github.com/ignitionrobotics/docs/blob/master/releases.md

**Comment by EricCousineau-TRI** [comment]
Huh... now that you mention it, I have no idea how I came across the wrong link <https://ignitionrobotics.org/docs/releases> - I don't think I typed it in, but in Firefox History, I can't seem to identify what my sites were referrers were at the time of the visit...

So yup, that sounds good! Want me to re-purpose this issue, or close it and open a more accurate one?

**Comment by chapulina** [comment]
> Want me to re-purpose this issue, or close it and open a more accurate one?

I'm fine either way, thanks!

**Comment by EricCousineau-TRI** [comment]
Repurposed!

**Comment by ahcorde** [comment]
@nkoenig I fixed this on the backend. Do you mind to have a look?

**Comment by scpeters** [comment]
Fix has been merged but not deployed

**Comment by chapulina** [comment]
Fixed: https://ignitionrobotics.org/docs/banana

**Comment by chapulina** [comment]
Spoke too soon, this pattern is still broken: https://ignitionrobotics.org/docs/latest/banana

CC @ahcorde

**Comment by ahcorde** [comment]
This PR fixed

 - /docs/<wrong_release>/install
 - /docs/citadel/< wrong tutorial >

https://gitlab.com/ignitionrobotics/web/web/-/merge_requests/20

**Comment by chapulina** [comment]
Thanks, I think we're all set now.
